### ISSUE TITLE
Hiding specific elements

### ISSUE THREAD

**Issue by jez-chaplin** [mongoose-marketplace/facebook-page-feed-graph-api#38]
Hi,

I'm hoping to be able to hide the top banner so that the first thing shown is the first post on the page - the css selector I can identify is #u_0_0 > div:nth-child(1) > div > div._2lqh

I can't seem to get this to hide and I suspect it's due to the plugin populating the page after page load and the css therefore not applying.

Is there another approach to hiding this element please?

Thanks,
Jeremy.
<img width="542" alt="screen shot 2017-09-28 at 20 26 33" src="https://user-images.githubusercontent.com/23535080/30986444-5c102dde-a48b-11e7-83f7-3350fd799c4a.png">

**Comment by cameronjonesweb** [comment]
Hi @jez-chaplin,

You can't apply CSS to the contents of an `iframe` when the source is on a different domain. If this was possible it would be a major security risk.
There's also no option to hide the header that Facebook provides unfortunately. I would recommend using the small header option which makes the header only 70px tall.

Thanks
